apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  type: NodePort
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 80          # The port the service listens on internally
      targetPort: 8080  # The port your Spring Boot app is running on
      nodePort: 30080   # The external port you will type in your browser!